name: Update submodules

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # Cron-based action
    schedule:
    # * is a special character in YAML so you have to quote this string
    # This example triggers the workflow every day at 5:30 and 17:30 UTC
    # https://crontab.cronhub.io/
    - cron: '*0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: windows-latest

        permissions:
          contents: write

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Check out from repository
              uses: actions/checkout@v3
              with:
                  # repository: {owner}/repo
                  token: ${{ secrets.GITHUB_TOKEN }}

            # Update references
            - name: Git Sumbodule Update
              run: |
                  git submodule update --init --force --remote

            # Commit
            - name: Commit update
              uses: stefanzweifel/git-auto-commit-action@v5
